/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubtitlesRouteImport } from './routes/subtitles'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CutterRouteImport } from './routes/cutter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'

const SubtitlesRoute = SubtitlesRouteImport.update({
  id: '/subtitles',
  path: '/subtitles',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CutterRoute = CutterRouteImport.update({
  id: '/cutter',
  path: '/cutter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cutter': typeof CutterRoute
  '/editor': typeof EditorRoute
  '/subtitles': typeof SubtitlesRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cutter': typeof CutterRoute
  '/editor': typeof EditorRoute
  '/subtitles': typeof SubtitlesRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cutter': typeof CutterRoute
  '/editor': typeof EditorRoute
  '/subtitles': typeof SubtitlesRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cutter' | '/editor' | '/subtitles' | '/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cutter' | '/editor' | '/subtitles' | '/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/cutter'
    | '/editor'
    | '/subtitles'
    | '/project/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CutterRoute: typeof CutterRoute
  EditorRoute: typeof EditorRoute
  SubtitlesRoute: typeof SubtitlesRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subtitles': {
      id: '/subtitles'
      path: '/subtitles'
      fullPath: '/subtitles'
      preLoaderRoute: typeof SubtitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutter': {
      id: '/cutter'
      path: '/cutter'
      fullPath: '/cutter'
      preLoaderRoute: typeof CutterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CutterRoute: CutterRoute,
  EditorRoute: EditorRoute,
  SubtitlesRoute: SubtitlesRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
